services:
  api:
    container_name: viprocAPI
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./src/appsettings.docker.json:/app/appsettings.json:ro
      - ./db:/app/db
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_HTTP_PORTS=80
      - ConnectionStrings__APIDBConnection=Data Source=/app/db/jobs.db
      - FFmpeg__BinaryPath=/usr/bin/ffmpeg
      - Security__ApiKeys__0="${API_KEY}"
      - Logging__LogLevel__Default=Information
      - RateLimit__MaxRequestsPerMinute=30
    depends_on:
      - minio
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  minio:
    image: minio/minio:latest
    ports:
      - "9005:9000" 
      - "9006:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin123
      - MINIO_REGION_NAME=us-east-1
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s
    command: server /data --console-address ":9001"

volumes:
  minio_data: