name: Integration Tests

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build application
      run: dotnet build --configuration Release --no-restore
      
    - name: Start Docker services for tests
      run: |
        docker-compose -f docker-compose.test.yml up -d
        # Wait for services to be ready
        sleep 30
        
    - name: Run integration tests
      run: dotnet test tests/VideoProcessingApi.IntegrationTests --configuration Release --no-build --verbosity normal --logger trx --results-directory TestResults
      
    - name: Stop Docker services
      if: always()
      run: docker-compose -f docker-compose.test.yml down
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results
        path: TestResults/
        retention-days: 7